In [36]:
import pandas as pd
import numpy as np

In [37]:
df = pd.read_csv("Company Attrition Data.csv")
df.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years  \
0                   3              0     1                      0   
1                   6              0     1                      0   
2                   4              0     1                      0   
3                   5              0     1                      0   
4                   3              0     1                      0   

  Sales_Occured  salary  
0         sales     low  
1         sales  medium  
2         sales  medium  
3         sales     low  
4         sales     low

In [38]:
df["left"].value_counts()

0    11428
1     3571
Name: left, dtype: int64

In [39]:
df.shape

(14999, 10)

In [40]:
s = 11428/(11428+3571)
print(s)

0.7619174611640777


In [41]:
df.describe()

satisfaction_level  last_evaluation  number_project  \
count        14999.000000     14999.000000    14999.000000   
mean             0.612834         0.716102        3.803054   
std              0.248631         0.171169        1.232592   
min              0.090000         0.360000        2.000000   
25%              0.440000         0.560000        3.000000   
50%              0.640000         0.720000        4.000000   
75%              0.820000         0.870000        5.000000   
max              1.000000         1.000000        7.000000   

       average_montly_hours  time_spend_company  Work_accident          left  \
count          14999.000000        14999.000000   14999.000000  14999.000000   
mean             201.050337            3.498233       0.144610      0.238083   
std               49.943099            1.460136       0.351719      0.425924   
min               96.000000            2.000000       0.000000      0.000000   
25%              156.000000            3.000000       0.000000      0.000000   
50%              200.000000            3.000000       0.000000      0.000000   
75%              245.000000            4.000000       0.000000      0.000000   
max              310.000000           10.000000       1.000000      1.000000   

       promotion_last_5years  
count           14999.000000  
mean                0.021268  
std                 0.144281  
min                 0.000000  
25%                 0.000000  
50%                 0.000000  
75%                 0.000000  
max                 1.000000

# Data Seperation

In [42]:
df.columns

Index(['satisfaction_level', 'last_evaluation', 'number_project',
       'average_montly_hours', 'time_spend_company', 'Work_accident', 'left',
       'promotion_last_5years', 'Sales_Occured', 'salary'],
      dtype='object')

In [43]:
X = df.loc[:,['satisfaction_level', 'last_evaluation', 'number_project',
       'average_montly_hours', 'time_spend_company', 'Work_accident',
       'promotion_last_5years', 'Sales_Occured', 'salary']]

In [44]:
X.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  promotion_last_5years Sales_Occured  \
0                   3              0                      0         sales   
1                   6              0                      0         sales   
2                   4              0                      0         sales   
3                   5              0                      0         sales   
4                   3              0                      0         sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low

In [45]:
y = df["left"]
y.head()

0    1
1    1
2    1
3    1
4    1
Name: left, dtype: int64

# Label Encoder

In [46]:
from sklearn.preprocessing import LabelEncoder, StandardScaler, MinMaxScaler
le=LabelEncoder()
ss=StandardScaler()
norm=MinMaxScaler()

In [47]:
X["Sales_Occured"]=le.fit_transform(X["Sales_Occured"])
X["salary"]=le.fit_transform(X["salary"])

In [48]:
X.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  promotion_last_5years  Sales_Occured  \
0                   3              0                      0              7   
1                   6              0                      0              7   
2                   4              0                      0              7   
3                   5              0                      0              7   
4                   3              0                      0              7   

   salary  
0       1  
1       2  
2       2  
3       1  
4       1

# Train_Test

In [49]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=100)

# Logistic Regression

In [58]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
from sklearn.metrics import accuracy_score

In [59]:
lr=LogisticRegression()

In [60]:
lr.fit(X_train,y_train)

C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [61]:
pred = lr.predict(X_test)
pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [62]:
y_test.head()

10155    0
11688    0
12598    1
12192    1
8678     0
Name: left, dtype: int64

In [63]:
accuracy_score(y_test,pred)

0.7688333333333334

# RFC Regression

In [73]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier

In [74]:
rfc =  RandomForestClassifier()
rfc.fit(X_train,y_train)
pred = rfc.predict(X_test)
accuracy_score(y_test,pred)

0.9908333333333333

In [75]:
print(accuracy_score(y_test,pred))

0.9908333333333333


# KNN Classifier

In [76]:
from sklearn.neighbors import KNeighborsClassifier

In [77]:
knn = KNeighborsClassifier(n_neighbors=4) 
# Here we can specify 4 things: n_neighbors, weights, algorithm and metric.
  
# Fitting the model
knn.fit(X_train, y_train) 
  
# Predict on dataset which model has not seen before 
y_pred = knn.predict(X_test)
print(y_pred) 

[0 0 1 ... 0 0 0]


In [81]:
from sklearn.metrics import confusion_matrix

In [78]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[4358,  204],
       [ 180, 1258]], dtype=int64)

In [79]:
knn = KNeighborsClassifier(n_neighbors=4)
from sklearn.model_selection import cross_val_score
# cross_val_score takes care of splitting X and y into the 15 folds that's why we pass X and y entirely instead of X_train and y_train
scores = cross_val_score(knn, X, y, cv=15, scoring='accuracy')
print(scores)

[0.936      0.944      0.924      0.931      0.945      0.912
 0.937      0.92       0.931      0.951      0.938      0.944
 0.965      0.953      0.96096096]


In [80]:
print(scores.mean())

0.939464064064064


# Decission Tree

In [85]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score

In [86]:
dfr=DecisionTreeRegressor(max_depth=8)
dfr.fit(X_train,y_train)
pred = dfr.predict(X_test)
r2_score(y_test,pred)

0.8886787398028402